package UI.Admin.MainAdmin;

public enum enAction {
    ADD_ADMIN,
    DELETE_ADMIN,
    UPDATE_ADMIN,
    ADD_CAST,
    DELETE_CAST,
    UPDATE_CAST,
    ADD_DIRECTOR,
    DELETE_DIRECTOR,
    UPDATE_DIRECTOR,
    ADD_MOVIE,
    CHECKING_REVENU_PER_MONTH,
    CHECKING_SYSTEM_STATS,
    SUSPEND_USER,
    USER_WITHDRAW_SUSPENSION
}
